eureka :
    client :
      service-url :
        defaultZone : http://localhost:8761/eureka/
spring :
  sql :
    init :
      mode : always
  datasource :
    url : jdbc:postgresql://localhost:5432/postgres
    username : postgres
    password : manav7776
    driver-class-name : org.postgresql.Driver
  #JPA & Hibernate related queries
  jpa :
    open-in-view : false
    hibernate :
      naming :
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto : update
    show-sql : true
    defer-datasource-initialization : true
  properties :
    hibernate :
      dialect : org.hibernate.dialect.PostgreSQLDialect
      format_sql : true
